name: Create diff

on:
  workflow_dispatch:
  workflow_call:

jobs:
  create-diff:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Create diff
      run: |
        git remote add AC https://github.com/azerothcore/azerothcore-wotlk.git
        git fetch AC master
        git diff AC/master > eluna.diff
    - name: Upload diff
      uses: actions/upload-artifact@v4
      with:
        name: eluna.diff
        path: |
          eluna.diff